### ISSUE TITLE
Write project development documentation

### ISSUE THREAD

**Issue by shizakken** [Ikken9/pencaucu#5]

**Comment by MartinCaraballo** [comment]
JOTA LEVANTA LA PALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by MartinCaraballo** [comment]
Y  APRENDE LATEX CHUPA VERGA
